version: '3'

services:
  wordpress:
    build: runtime/wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: TtRBdkJrQ38DxX
      WORDPRESS_DB_NAME: 61src
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "wordpress:/var/www/html"

  db:
    image: mariadb:10.10.3-jammy
    restart: always
    environment:
      MARIADB_DATABASE: 61src
      MARIADB_ROOT_PASSWORD: TtRBdkJrQ38DxX
    volumes:
      - "db:/var/lib/mysql"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db:
  wordpress: